
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0.39
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    expose:
      - 3306
    volumes:
      - ./mysql/mysql-volume:/var/lib/mysql
      